# Generated by Django 5.1.6 on 2025-04-20 17:17

import django.core.validators
import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('mp3', models.FileField(blank=True, null=True, upload_to=sermons.models.mp3_sermon_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('video', models.FileField(blank=True, null=True, upload_to=sermons.models.mp4_sermon_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])])),
                ('video_link', models.URLField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=sermons.models.mp4_sermon_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'giff'])])),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('scriptures', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
