# Generated by Django 5.1.6 on 2025-04-05 08:55

import django.core.validators
import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=sermons.models.mp4_sermon_directory,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "avi"]
                    )
                ],
            ),
        ),
    ]
