# Generated by Django 5.1.6 on 2025-04-05 19:27

import django.core.validators
import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0002_alter_sermon_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="scriptures",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="series",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=sermons.models.mp4_sermon_directory,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg", "giff"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="video_link",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
