# Generated by Django 5.1.6 on 2025-04-17 19:15

import datetime
from django.utils  import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="date",
            field=models.DateField(default=datetime.date(2025, 4, 17)),
        ),
        migrations.AddField(
            model_name="events",
            name="time",
            field=models.TimeField(default=timezone.now()),
        ),
    ]
