# Generated by Django 5.1.6 on 2025-04-18 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events_date_events_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="events",
            name="time",
            field=models.TimeField(default="09:01"),
        ),
    ]
