# Generated by Django 5.1.6 on 2025-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_fellowship"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
