# Generated by Django 5.1.6 on 2025-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_fellowship_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
