# Generated by Django 5.1.6 on 2025-04-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_customuser_activation_code_customuser_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("leader", "Leader"),
                    ("media", "Media"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
