# Generated by Django 5.1.6 on 2025-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="born_again",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="martial_status",
            field=models.CharField(
                choices=[
                    ("married", "Married"),
                    ("single", "Single"),
                    ("divorced", "Divorced"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
