# Generated by Django 5.1.6 on 2025-03-29 20:18

import django.db.models.deletion
import django.utils.timezone
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='Not provided', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimony',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testimony',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.customuser'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='category',
            field=models.CharField(choices=[('healing', 'Healing'), ('salvation', 'Salvation'), ('deliverance', 'Deliverance'), ('provision', 'Provision'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.Testimony.testimony_image_path),
        ),
    ]
