# Generated by Django 5.1.6 on 2025-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_profile_born_again_profile_martial_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimony",
            old_name="testimony",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="testimony",
            old_name="approved",
            new_name="verified",
        ),
        migrations.AddField(
            model_name="testimony",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
